### ISSUE TITLE
Book7_Ch07_Page10

### ISSUE THREAD

**Issue by liujunfeng1998** [Visualize-ML/Book7_Machine-Learning#16]
<img width="472" alt="image" src="https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/87808990/758171e9-409d-42ac-95bc-a04ffc31aaa1">
A、B和C写反了，应该是A和B在l2上，C在l1上

**Comment by liujunfeng1998** [comment]
Book7_Ch09_Page10
<img width="1209" alt="image" src="https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/87808990/c9addac8-2657-4adc-ad4d-842a5b85cfb3">

应该是根据。以及是否应该是信息增益最大化原则或者基尼指数最小化原则？

**Comment by Visualize-ML** [comment]
谢谢你，2024年将统一修改Book7。请继续批评指正。

Cheers,
James

**Comment by Visualize-ML** [comment]
谢谢你，已经修改。请继续批评指正。
