### ISSUE TITLE
Book7_Ch07_Page12

### ISSUE THREAD

**Issue by kwitter777** [Visualize-ML/Book7_Machine-Learning#17]
![image](https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/48406178/078e52de-ebda-413f-a751-6299ace118b1)
![image](https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/48406178/ae6ae188-a13e-4bd2-92f0-90fc77d134ff)
这里公式（21）应该是由公式（17）的简化计算的设置推到出来的吧，而不是公式（18）

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了。2024年统一修改。请继续批评指正。

**Comment by Visualize-ML** [comment]
已经修改，请继续批评指正。
