### ISSUE TITLE
Ch13

### ISSUE THREAD

**Issue by superwjfeng** [Visualize-ML/Book7_Machine-Learning#2]
Ch13 Page4 公式5下方的段落中，我猜测应该是图3而不是图9？

**Comment by Visualize-ML** [comment]
已经修改，谢谢你！请继续指正。

**Comment by Visualize-ML** [comment]
感谢你对鸢尾花书的支持，清华社安排了赠书活动。

活动页面：
https://zhuanlan.zhihu.com/p/622091048
