### ISSUE TITLE
第03章-多元线性回归

### ISSUE THREAD

**Issue by DanielXYZJohnson** [Visualize-ML/Book7_Machine-Learning#21]
![9491dc5df4d1336c5ccdb7f18842b03](https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/139046386/c875aed5-d6a9-427a-a7bc-a84e0ae63cd6)

这个是爱默生的生卒年吗？维基百科显示生卒年是1803~1882

![image](https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/139046386/86ebe7f3-d338-4c13-884a-6947d33265f3)

**Comment by Visualize-ML** [comment]
确实写错了，纸质书已经修改
