### ISSUE TITLE
第24章 密度聚类

### ISSUE THREAD

**Issue by Hologram-Rose** [Visualize-ML/Book7_Machine-Learning#22]
在思维导图中，密度聚类写成了层次聚类。
![Quicker_20240403_113707](https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/73545438/e68303c5-56e8-4ebe-8cc7-e8b11190692e)

**Comment by Visualize-ML** [comment]
确实写错了，纸质书已经修改
