### ISSUE TITLE
Book7_Ch02_回归分析

### ISSUE THREAD

**Issue by AOMJ2PMP** [Visualize-ML/Book7_Machine-Learning#23]
![勘误](https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/107308972/43fa3833-23cd-4cfe-aa67-f72ee8261d13)
红色部分应该为《统计至简》

**Comment by Visualize-ML** [comment]
谢谢你，这个错误先开着；校对时，统一修改。

**Comment by Visualize-ML** [comment]
纸质书已经修改，谢谢
