### ISSUE TITLE
Book7_Ch09_Page3

### ISSUE THREAD

**Issue by uiloatoat** [Visualize-ML/Book7_Machine-Learning#24]
姜兄好！Book7_Ch09_Page3下图中有个小错误
![1715572416991](https://github.com/Visualize-ML/Book7_Visualizations-for-Machine-Learning/assets/128017754/ed0a74e6-97dd-45b9-bc1b-f751a21d11ea)
圆圈中应为 $f_{Y|\chi}(C_2\mid x)$

**Comment by Visualize-ML** [comment]
谢谢你，确实有误；这个错误先开一下，等到校对这本时统一修改，也请继续批评指正。

**Comment by Visualize-ML** [comment]
纸质书已经修改
